hss:
  enabled: false

mme:
  enabled: false

pcrf:
  enabled: false

smf:
  config:
    pcrf:
      enabled: false

sgwc:
  enabled: false

sgwu:
  enabled: false

amf:
  config:
    guamiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        amf_id:
          region: 2
          set: 1
    taiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        tac: [1]
    plmnList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        s_nssai:
          - sst: 1
            sd: "0x111111"

nssf:
  config:
    nsiList:
      - uri: ""
        sst: 1
        sd: "0x111111"

webui:
  ingress:
    enabled: false

populate:
  enabled: true
  initCommands:
  - open5gs-dbctl add_ue_with_slice 999700000000001 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111
  - open5gs-dbctl add_ue_with_slice 999700000000002 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111

mongodb:
  enabled: false
  auth:
    enabled: false
  image:
    registry: docker.io
    repository: ujemnadelta/mongodb-rbpi
    tag: 7.0.4
    pullPolicy: IfNotPresent
    debug: true
#  persistence:
#    storageClass: "path-local"

#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: open5gs-mongodb-pv
#  namespace: "default"
#  labels:
#    app.kubernetes.io/name: mongodb
#    helm.sh/chart: mongodb-12.1.31
#    app.kubernetes.io/instance: open5gs
#    app.kubernetes.io/managed-by: Helm
#    app.kubernetes.io/component: mongodb
#  spec:
#    accessModes:
#      - "ReadWriteOnce"
#    capacity:
#      storage: "8Gi"
#    persistentVolumeReclaimPolicy: Retain
#    storageClassName: standard
