hss:
  enabled: false

mme:
  enabled: false

pcrf:
  enabled: false

smf:
  config:
    pcrf:
      enabled: false

sgwc:
  enabled: false

sgwu:
  enabled: false

amf:
  config:
    guamiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        amf_id:
          region: 2
          set: 1
    taiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        tac: [1]
    plmnList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        s_nssai:
          - sst: 1
            sd: "0x111111"

nssf:
  config:
    nsiList:
      - uri: ""
        sst: 1
        sd: "0x111111"

webui:
  ingress:
    enabled: false
  image:
    registry: docker.io
    repository: ujemnadelta/open5gs-webui
    tag: 2.7.2-arm64
    pullPolicy: Always
#  image:
#    registry: docker.io
#    repository: gradiant/open5gs-webui
#    tag: 2.7.2
#    pullPolicy: Always

populate:
  enabled: true
  initCommands:
  - open5gs-dbctl add_ue_with_slice 999700000000001 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111
  - open5gs-dbctl add_ue_with_slice 999700000000002 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111
  - open5gs-dbctl add_ue_with_slice 999700000000003 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111

mongodb:
  enabled: false
  auth:
    enabled: false
  image:
    registry: docker.io
    repository: ujemnadelta/mongodb-rbpi
    tag: 7.0.4
    pullPolicy: IfNotPresent
    debug: true

# trying to set up multiple UPFs:

#smf:
#  config:
#    session:
#      - subnet: 10.45.0.1/16
#        dnn: internet
#      - subnet: 10.46.0.1/16
#        dnn: internet2
#    upf:
#      pfcp:
#    pfcp:
#      client:
#        upf:
#          - address: 127.0.0.7
#            dnn: internet
#          - address: 127.0.0.8
#            dnn: internet2
#    pcrf:
#      enabled: false

upf:
  config:
    pfcp:
      server:
        - address: 127.0.0.7
      client:
        smf:
          - address: 127.0.0.4
#    session:
#      - address: 10.45.0.1/16
#        dnn: internet
#        dev: ogstun
    session:
      - subnet: 10.45.0.0/16
        gateway: 10.45.0.1
        dnn: internet
      - subnet: 2001:db8:cafe::/48
        dnn: internet
        dev: ogstun2
      - subnet: 10.46.0.0/16
        gateway: 10.46.0.1
        dnn: ims
        dev: ogstun3
      - subnet: 2001:db8:babe::/48
        dnn: ims
        dev: ogstun3

upf-2:
  config:
    pfcp:
      server:
        - address: 127.0.0.8
      client:
        smf:
          - address: 127.0.0.4
    session:
      - address: 10.45.0.2/16
        dnn: internet
        dev: ogstun2
#      - addr: 10.45.0.2/16
#        dnn: internet
#        dev: ogstun2
